### ISSUE TITLE
祝福卡片邏輯

### ISSUE THREAD

**Issue by teda0001** [zheung/KairiQuery#8]
祝福的技能ID藏在 card.csv[i][32] 、按普通技能處理邏輯來搞就可以了，實現起來應該不太困難 ＿(：3 」∠)＿ 

（順帶一提圓桌卡的初手必中效果是以ex技藏在 card.csv[i][33]）

**Comment by zheung** [comment]
感谢帮忙!

祝福技能本身的渲染不是问题，如你所说和普通技能一样就好。
主要是一些时机的描述。例如没亲身使用过召唤石，就不知道触发时机有两种之类的。

原来那一列是这样用的啊。虽然一直知道是被动技能列，但还真没仔细研究过里面的值。
毕竟祝福啊召唤石啊之类的新东西一直拖着没写出来（打死

**Comment by teda0001** [comment]
我自己是懒，不想每次更新的时候都要自己手动打一大堆效果，所以每次有新效果几乎都要(被逼)解出来。
好象KairiQuery那样能全自动解包是我的梦想呢XDD
